name: check_oks

on:
  push:
    branches: [ "master" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: composer install --working-dir=./src
      - run: ./src/vendor/bin/phpunit ./src/tests
      - run: ./src/vendor/bin/grumphp run
